#!/usr/bin/env bash
# Stop hook — queues session transcript to task_queue (target=cowork) for Iris to process.
# Reads transcript_path from Stop hook JSON input (stdin).

# Load credentials from env file (never hardcode secrets in tracked files)
ENV_FILE="/home/almty1/azlab/services/memory-mcp-server/.env"
if [[ -f "$ENV_FILE" ]]; then
  set -o allexport
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +o allexport
fi

SUPABASE_URL="${SUPABASE_URL:-}"
# Post-4/30 rotation: new sb_secret_ key is SUPABASE_SECRET_KEY; legacy name as fallback.
SERVICE_KEY="${SUPABASE_SECRET_KEY:-${SUPABASE_SERVICE_KEY:-}}"

if [[ -z "$SUPABASE_URL" || -z "$SERVICE_KEY" ]]; then
  exit 0
fi

# Read Stop hook JSON from stdin
HOOK_JSON=$(cat)

TRANSCRIPT_PATH=$(echo "$HOOK_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('transcript_path',''))" 2>/dev/null || true)
SESSION_ID=$(echo "$HOOK_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('session_id',''))" 2>/dev/null || true)

if [[ -z "$TRANSCRIPT_PATH" || ! -f "$TRANSCRIPT_PATH" ]]; then
  exit 0
fi

# --- Loop/flood guard (added 2026-07-10) ---
# Only hand off transcripts from GENUINE INTERACTIVE Wren sessions.
# Skip automated sessions:
#   * entrypoint "sdk-cli"  -> SDK/programmatic runs, incl. the Argus workers
#     that PROCESS these very tasks. Without this gate each processing worker
#     re-queues another transcript task = self-perpetuating loop.
#   * sessionKind "bg"      -> background timer-driven agents (watchdog, pollers,
#     research/dashboard agents) that Stop constantly.
#   * watchdog-canary-*     -> the wren-watchdog health-probe session. It launches as
#     entrypoint "cli" with NO bg flag, so the two checks above miss it; it fires every
#     ~2 min and was the dominant source of the transcript-task flood (90-170/day, see
#     feedback_empty_autogenerated_tasks_not_surfaced_to_jeff). Match its canary PROMPT
#     ("# watchdog-canary-<ts>") specifically — a bare "watchdog-canary" substring also
#     appears in genuine sessions that merely discuss the watchdog, so anchor on the
#     markdown-heading prompt form to avoid skipping real interactive handoffs.
# Interactive Wren TUI sessions are entrypoint "cli" with no bg flag.
if grep -qE '"entrypoint":"sdk-cli"|"sessionKind":"bg"|# watchdog-canary-[0-9]' "$TRANSCRIPT_PATH" 2>/dev/null; then
  echo "transcript-on-stop: skipping non-interactive session ($TRANSCRIPT_PATH)" >&2
  exit 0
fi

# --- Watchdog-canary guard (added 2026-07-12) ---
# The discord-bridge/watchdog session is entrypoint "cli" with human-typed
# "# watchdog-canary-<epoch>" heartbeat prompts and NO bg flag, so it slipped
# the gate above and re-queued a canary-only transcript on every ~10-min ping
# (260+ junk rows, 100% of ready/review_needed as of 2026-07-12). Skip any
# session whose final prompt is a watchdog-canary heartbeat — those contain no
# real work to extract.
if grep -qE '"lastPrompt":"[# ]*watchdog-canary' "$TRANSCRIPT_PATH" 2>/dev/null; then
  echo "transcript-on-stop: skipping watchdog-canary heartbeat session ($TRANSCRIPT_PATH)" >&2
  exit 0
fi

SESSION_DATE=$(date +%Y-%m-%d)

# Get last 4000 chars of transcript
TRANSCRIPT_TAIL=$(python3 -c "
content = open('$TRANSCRIPT_PATH', 'r', errors='replace').read()
print(content[-4000:])
" 2>/dev/null || true)

if [[ -z "$TRANSCRIPT_TAIL" ]]; then
  exit 0
fi

# Build payload safely via python
PAYLOAD=$(python3 - <<PYEOF
import json, sys

transcript = open('$TRANSCRIPT_PATH', 'r', errors='replace').read()[-4000:]
ctx = {
    'transcript': transcript,
    'agent': 'wren',
    'session_date': '$SESSION_DATE',
    'session_id': '$SESSION_ID'
}
task = {
    'title': 'Process session transcript',
    'description': 'Session transcript handoff from Wren ($SESSION_DATE) — review the transcript in context and extract any memories, decisions, or follow-up items. (task_queue.description is NOT NULL — this field is required.)',
    'target': 'cowork',
    'source': 'claude-code',
    'priority': 2,
    'context': ctx,
    'tags': ['transcript']
}
print(json.dumps(task))
PYEOF
)

if [[ -z "$PAYLOAD" ]]; then
  exit 0
fi

# --- Per-session dedup (added 2026-07-24) ---
# Stop fires on EVERY turn-stop, not once per session, so a single long
# interactive session queued one transcript task per turn — 3 identical rows
# from session 320d4978 on 2026-07-24 alone (see
# project_transcript_on_stop_loop_fix_20260710, 3rd recurrence).
# If this session already has an UNCLAIMED transcript task, refresh its context
# with the newer tail instead of inserting a duplicate. If the earlier row was
# already claimed/completed, no rows match and we fall through to a fresh
# enqueue — the later work still gets handed off.
if [[ -n "$SESSION_ID" ]]; then
  UPDATED=$(curl -s -m 8 -X PATCH \
    "${SUPABASE_URL}/rest/v1/task_queue?context->>session_id=eq.${SESSION_ID}&status=in.(pending,ready)&tags=cs.%7Btranscript%7D" \
    -H "apikey: ${SERVICE_KEY}" \
    -H "Authorization: Bearer ${SERVICE_KEY}" \
    -H "Content-Type: application/json" \
    -H "Prefer: return=representation" \
    -d "$(python3 -c "
import json,sys
task = json.loads(sys.stdin.read())
print(json.dumps({'context': task['context']}))
" <<<"$PAYLOAD")" 2>/dev/null)

  if [[ -n "$UPDATED" && "$UPDATED" != "[]" ]]; then
    echo "transcript-on-stop: refreshed existing transcript task for session $SESSION_ID" >&2
    exit 0
  fi
fi

# Prefer the validating task-queue Worker (enforces title/description + schema,
# retries -> DLQ). Fall back to a direct Supabase insert if the Worker is
# unreachable so a transcript is never lost during migration. Failures are
# logged to stderr (journald), NOT silently swallowed.
WORKER_URL="https://az-task-queue-worker.almty1.workers.dev/enqueue"
INGEST_SECRET=$(cat "$HOME/.cloudflare/ingest-secret" 2>/dev/null)

HTTP=$(curl -s -m 6 -o /dev/null -w '%{http_code}' -X POST "$WORKER_URL" \
  -H "x-ingest-secret: ${INGEST_SECRET}" \
  -H "Content-Type: application/json" \
  -d "$PAYLOAD" 2>/dev/null)

if [[ "$HTTP" != "202" ]]; then
  echo "transcript-on-stop: worker enqueue failed (HTTP ${HTTP:-000}); falling back to direct insert" >&2
  curl -s -m 8 -X POST "${SUPABASE_URL}/rest/v1/task_queue" \
    -H "apikey: ${SERVICE_KEY}" \
    -H "Authorization: Bearer ${SERVICE_KEY}" \
    -H "Content-Type: application/json" \
    -d "$PAYLOAD" >/dev/null 2>&1 \
    || echo "transcript-on-stop: fallback direct insert ALSO failed" >&2
fi

exit 0
