version: "3.9"

services:
  traefik:
    image: docker.io/traefik:v3.6
    container_name: traefik
    restart: unless-stopped

    networks:
      - proxy

    dns:
      - 1.1.1.1
      - 8.8.8.8

    ports:
      - "80:80"
      - "443:443"

    env_file:
      - ./cf.env

    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
      - ./data:/data
      - ./secrets:/secrets:ro
      - ./dynamic:/dynamic:ro
      - ./certs:/certs:ro

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.az-lab.dev`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.middlewares.traefik-allow.ipallowlist.sourcerange=192.168.1.0/24,10.7.0.0/24,10.89.0.0/16"
      - "traefik.http.routers.traefik.middlewares=traefik-allow,authelia-auth@file,strip-www-auth@file"

    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--api.dashboard=true"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"

      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"

      - "--certificatesresolvers.le.acme.email=almty1@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.dnschallenge.propagation.delaybeforechecks=10"
      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"

networks:
  proxy:
    external: true
