tls:
  certificates:
    - certFile: /certs/home-arpa.crt
      keyFile: /certs/home-arpa.key

http:
  routers:
    home-arpa:
      rule: HostRegexp(`{host:.+\.home\.arpa}`)
      entryPoints:
        - websecure
      priority: 40
      service: home-arpa

  services:
    home-arpa:
      loadBalancer:
        servers:
          - url: http://192.168.1.181
        passHostHeader: true
