-- 095_schema_export_rpc.sql
-- 2026-08-01 daily research, REC 1.3 (the forward fix for the 093 data-loss hole).
--
-- ============================================================================
-- WHY
-- ============================================================================
-- services/backups/bin/supabase-export.py enumerates public tables via the
-- PostgREST OpenAPI spec and writes <table>.json.gz. Rows only. No pg_dump,
-- no function DDL, no index or constraint DDL. Restoring from that backup gives
-- you every memory row and NO ranker to retrieve them with -- see 093 for how
-- close that came to being an unrecoverable loss.
--
-- There is no direct Postgres connection on svc-podman-01 (the backup unit holds
-- SUPABASE_URL + SUPABASE_SECRET_KEY only, no DATABASE_URL), so `pg_dump
-- --schema-only` is not available to the nightly. This RPC gives the existing
-- REST-only auth model a schema lane without introducing a second credential.
--
-- ============================================================================
-- WHAT
-- ============================================================================
-- public.export_schema_ddl() returns the full public-schema DDL as text:
--   extensions, tables, constraints, indexes, views, functions/procedures
--   (pg_get_functiondef -- the ranker), triggers, RLS policies.
-- ~248 KB as of 2026-08-01.
--
-- SECURITY DEFINER because pg_get_functiondef on other roles' objects needs it.
-- It exposes DDL only -- never row data -- and EXECUTE is revoked from PUBLIC,
-- anon and authenticated, leaving service_role (which the backup unit already
-- holds, and which could read everything anyway).
--
-- Consumed by supabase-export.py, which writes it to schema.sql.gz beside the
-- table JSON in each dated backup directory.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.export_schema_ddl()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  out_txt text := '';
BEGIN
  out_txt := out_txt || E'-- ============================================================\n'
                     || E'-- azlab-memory schema DDL snapshot\n'
                     || E'-- Generated by public.export_schema_ddl()\n'
                     || E'-- ============================================================\n\n';

  out_txt := out_txt || E'\n-- ===================== EXTENSIONS =====================\n';
  SELECT out_txt || coalesce(string_agg(
           format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;', e.extname, n.nspname),
           E'\n' ORDER BY e.extname), '')
    INTO out_txt
    FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace;

  out_txt := out_txt || E'\n\n-- ===================== TABLES =====================\n';
  SELECT out_txt || coalesce(string_agg(t.ddl, E'\n\n' ORDER BY t.relname), '') INTO out_txt
  FROM (
    SELECT c.relname,
           format(E'-- table: %I\nCREATE TABLE IF NOT EXISTS public.%I (\n%s\n);',
             c.relname, c.relname,
             (SELECT string_agg(
                        format('  %I %s%s%s', a.attname,
                               format_type(a.atttypid, a.atttypmod),
                               CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
                               CASE WHEN ad.adbin IS NOT NULL
                                    THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
                                    ELSE '' END),
                        E',\n' ORDER BY a.attnum)
                FROM pg_attribute a
                LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
               WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped)) AS ddl
      FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND c.relkind = 'r'
  ) t;

  out_txt := out_txt || E'\n\n-- ===================== CONSTRAINTS =====================\n';
  SELECT out_txt || coalesce(string_agg(
           format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;',
                  cl.relname, con.conname, pg_get_constraintdef(con.oid)),
           E'\n' ORDER BY cl.relname, con.conname), '') INTO out_txt
    FROM pg_constraint con
    JOIN pg_class cl ON cl.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = cl.relnamespace
   WHERE n.nspname = 'public';

  out_txt := out_txt || E'\n\n-- ===================== INDEXES =====================\n';
  SELECT out_txt || coalesce(string_agg(pg_get_indexdef(i.indexrelid) || ';',
                                        E'\n' ORDER BY ic.relname), '') INTO out_txt
    FROM pg_index i
    JOIN pg_class ic ON ic.oid = i.indexrelid
    JOIN pg_namespace n ON n.oid = ic.relnamespace
   WHERE n.nspname = 'public' AND NOT i.indisprimary
     AND NOT EXISTS (SELECT 1 FROM pg_constraint c2 WHERE c2.conindid = i.indexrelid);

  out_txt := out_txt || E'\n\n-- ===================== VIEWS =====================\n';
  SELECT out_txt || coalesce(string_agg(
           format(E'CREATE OR REPLACE VIEW public.%I AS\n%s',
                  c.relname, pg_get_viewdef(c.oid, true)),
           E'\n\n' ORDER BY c.relname), '') INTO out_txt
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relkind IN ('v','m');

  out_txt := out_txt || E'\n\n-- ===================== FUNCTIONS =====================\n';
  SELECT out_txt || coalesce(string_agg(pg_get_functiondef(p.oid) || E';\n',
                    E'\n' ORDER BY p.proname, p.oid::regprocedure::text), '') INTO out_txt
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = 'public' AND p.prokind IN ('f','p');

  out_txt := out_txt || E'\n\n-- ===================== TRIGGERS =====================\n';
  SELECT out_txt || coalesce(string_agg(pg_get_triggerdef(tg.oid) || ';',
                                        E'\n' ORDER BY cl.relname, tg.tgname), '') INTO out_txt
    FROM pg_trigger tg
    JOIN pg_class cl ON cl.oid = tg.tgrelid
    JOIN pg_namespace n ON n.oid = cl.relnamespace
   WHERE n.nspname = 'public' AND NOT tg.tgisinternal;

  out_txt := out_txt || E'\n\n-- ===================== RLS POLICIES =====================\n';
  SELECT out_txt || coalesce(string_agg(
           format('CREATE POLICY %I ON public.%I AS %s FOR %s TO %s%s%s;',
                  pol.polname, cl.relname,
                  CASE pol.polpermissive WHEN true THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END,
                  CASE pol.polcmd WHEN 'r' THEN 'SELECT' WHEN 'a' THEN 'INSERT'
                                  WHEN 'w' THEN 'UPDATE' WHEN 'd' THEN 'DELETE' ELSE 'ALL' END,
                  coalesce((SELECT string_agg(quote_ident(rolname), ', ')
                              FROM pg_roles WHERE oid = ANY(pol.polroles)), 'PUBLIC'),
                  coalesce(' USING (' || pg_get_expr(pol.polqual, pol.polrelid) || ')', ''),
                  coalesce(' WITH CHECK (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')', '')),
           E'\n' ORDER BY cl.relname, pol.polname), '') INTO out_txt
    FROM pg_policy pol
    JOIN pg_class cl ON cl.oid = pol.polrelid
    JOIN pg_namespace n ON n.oid = cl.relnamespace
   WHERE n.nspname = 'public';

  RETURN out_txt || E'\n';
END;
$function$
;

REVOKE ALL ON FUNCTION public.export_schema_ddl() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.export_schema_ddl() FROM anon;
REVOKE ALL ON FUNCTION public.export_schema_ddl() FROM authenticated;
GRANT EXECUTE ON FUNCTION public.export_schema_ddl() TO service_role;
