-- 137_conflict_sweep_pit_head_of_line.sql — 2026-08-26
--
-- WHAT WAS ACTUALLY BROKEN (measured 2026-08-26, task "unblock the conflict sweep")
--   Migration 133 made resolve_conflict_auto() return action='skipped' for any
--   non-'stale' conflict touching an is_point_in_time row. That guard is correct.
--   What it never does is mark the conflict resolved — correctly so, since whether
--   a PIT pair should be retired is a human call, not the resolver's.
--
--   sweep_conflicts() selects its candidates:
--       WHERE NOT resolved ORDER BY created_at ASC LIMIT p_limit
--   So every night the same permanently-unresolvable PIT conflicts are re-selected
--   from the FRONT of an age-ordered queue and re-skipped. They are head-of-line
--   blockers: they consume the 200-row budget and are still there tomorrow.
--
--   Measured saturation series from contradiction_scan.log (`skipped` of 200):
--       2026-08-24 03:30   skipped   0   open_after   6    (pre-133)
--       2026-08-25 03:20   skipped  60   open_after 178
--       2026-08-25 03:30   skipped 124   open_after 133
--       2026-08-26 03:30   skipped 140   open_after 276
--       2026-08-26 05:01   skipped 157   open_after 264
--   Candidate window at 2026-08-26 (oldest 200 open): 166 PIT-deferrable,
--   34 reachable. Whole open set: 328 open, 224 PIT-deferrable, 104 reachable.
--   Extrapolated, the sweep reaches ZERO adjudicable work and still exits 0,
--   because `processed` is pinned at the constant 200 and nothing reads `skipped`.
--
-- WHAT THIS MIGRATION CHANGES (availability only)
--   1. conflict_sweep_queue — one view that decides, in ONE place, whether a
--      conflict is PIT-deferrable. The predicate mirrors resolve_conflict_auto()
--      exactly, including the two arms that run BEFORE the 133 guard:
--        * conflict_type='stale' is CASE A and never reaches the guard, so a
--          stale conflict touching a PIT row is still adjudicable (15 of the 181
--          PIT-touching rows in the 08-26 window are this).
--        * a conflict with a deleted side is closed_moot before the guard, so it
--          must stay a candidate.
--   2. sweep_conflicts() draws candidates from that view with pit_deferred=false.
--      Nothing else changes: same signature, same per-row exception handling,
--      same resolve_conflict_auto() call, no conflict_flagged value touched, and
--      NO PIT conflict is marked resolved. They stay open and visible — the
--      x0.75 governance question is deliberately left to Jeff.
--   3. conflict_sweep_runs — the skipped-vs-processed split persisted as a series
--      so saturation is visible before it is total, plus conflict_sweep_health
--      to read it. Previously this signal existed only in a log line nobody read.
--
-- Idempotent. No conflict row is resolved, no memory row is modified.

-- ── 1. Candidate view: the single definition of "the resolver will refuse this" ──
CREATE OR REPLACE VIEW public.conflict_sweep_queue
WITH (security_invoker = true) AS
SELECT c.id,
       c.conflict_type,
       c.created_at,
       -- Mirrors the migration-133 guard in resolve_conflict_auto(), which sits
       -- AFTER the moot check and AFTER CASE A. Both exclusions matter:
       (c.conflict_type IS DISTINCT FROM 'stale'
        AND ma.id IS NOT NULL AND mb.id IS NOT NULL
        AND (COALESCE(ma.is_point_in_time, false) OR COALESCE(mb.is_point_in_time, false))
       ) AS pit_deferred
FROM memory_conflicts c
LEFT JOIN memories ma ON ma.id = c.memory_a_id
LEFT JOIN memories mb ON mb.id = c.memory_b_id
WHERE COALESCE(c.resolved, false) = false;

COMMENT ON VIEW public.conflict_sweep_queue IS
  'Open conflicts with pit_deferred: true when resolve_conflict_auto() would return action=''skipped'' on the migration-133 point-in-time guard without ever resolving the row. sweep_conflicts() takes candidates from pit_deferred=false. Deferred rows stay OPEN on purpose — retiring a point-in-time record is a human call (migration 137).';

REVOKE ALL ON public.conflict_sweep_queue FROM anon, authenticated;

-- ── 2. Saturation series ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.conflict_sweep_runs (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ran_at               timestamptz NOT NULL DEFAULT now(),
  actor                text        NOT NULL,
  sweep_limit          integer     NOT NULL,
  open_before          integer     NOT NULL,
  candidates_available integer     NOT NULL,  -- open AND NOT pit_deferred, pre-run
  pit_deferred         integer     NOT NULL,  -- open AND pit_deferred, pre-run
  processed            integer     NOT NULL,
  adjudicated          integer     NOT NULL,  -- processed - skipped - errors
  skipped              integer     NOT NULL,
  errors               integer     NOT NULL,
  actions              jsonb       NOT NULL,
  open_after           integer     NOT NULL
);

COMMENT ON TABLE public.conflict_sweep_runs IS
  'One row per sweep_conflicts() call (migration 137). Read `adjudicated` and `skipped`, NOT `processed` — processed is pinned at the p_limit constant whenever the queue is saturated and therefore reads healthy while the sweep does nothing.';

CREATE INDEX IF NOT EXISTS conflict_sweep_runs_ran_at_idx
  ON public.conflict_sweep_runs (ran_at DESC);

ALTER TABLE public.conflict_sweep_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.conflict_sweep_runs FROM anon, authenticated;

DROP VIEW IF EXISTS public.conflict_sweep_health;
CREATE VIEW public.conflict_sweep_health
WITH (security_invoker = true) AS
SELECT r.ran_at,
       r.actor,
       r.open_before,
       r.open_after,
       (r.open_before - r.open_after)            AS net_closed,
       r.candidates_available,
       r.pit_deferred,
       r.processed,
       r.adjudicated,
       r.skipped,
       r.errors,
       round(100.0 * r.skipped / NULLIF(r.processed, 0), 1)    AS skipped_pct,
       round(100.0 * r.pit_deferred / NULLIF(r.open_before, 0), 1) AS deferred_pct_of_open,
       GREATEST(0, r.candidates_available - r.processed)       AS backlog_unreached,
       -- See 137a: adjudicated=0 under budget is a permanent refused residue,
       -- NOT budget exhaustion. Collapsing the two would repeat the very error
       -- this migration exists to fix.
       CASE
         WHEN r.processed = 0 AND r.candidates_available = 0 THEN 'idle — nothing adjudicable open'
         WHEN r.processed = 0                                THEN 'NOT RUNNING — candidates exist, none processed'
         WHEN r.adjudicated = 0 AND r.processed >= r.sweep_limit
              THEN 'SATURATED — full budget spent, zero adjudicated'
         WHEN r.adjudicated = 0
              THEN 'STALLED — every candidate refused or errored (under budget)'
         WHEN r.candidates_available > r.processed
              THEN 'BACKLOG — adjudicable work exceeded the budget'
         WHEN r.open_after > r.open_before                    THEN 'intake exceeds resolution this run'
         ELSE 'ok'
       END AS verdict
FROM public.conflict_sweep_runs r
ORDER BY r.ran_at DESC;

COMMENT ON VIEW public.conflict_sweep_health IS
  'Saturation readout over conflict_sweep_runs (migration 137). verdict distinguishes "no adjudicable work left" from "budget burned on rows the resolver refuses" — the 08-25/08-26 failure looked identical to healthy in the log because both report processed=200.';

REVOKE ALL ON public.conflict_sweep_health FROM anon, authenticated;

-- ── 3. Sweep driver: skip-aware candidate set + telemetry ────────────────────
CREATE OR REPLACE FUNCTION public.sweep_conflicts(
  p_limit integer DEFAULT 200,
  p_actor text    DEFAULT 'conflict-sweep',
  p_types text[]  DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $$
DECLARE
  r            RECORD;
  v_res        jsonb;
  v_actions    jsonb := '{}'::jsonb;
  v_action     text;
  v_total      integer := 0;
  v_errors     integer := 0;
  v_skipped    integer := 0;
  v_open_before integer;
  v_open_after  integer;
  v_available  integer;
  v_deferred   integer;
BEGIN
  SELECT count(*),
         count(*) FILTER (WHERE NOT q.pit_deferred
                            AND (p_types IS NULL OR q.conflict_type = ANY(p_types))),
         count(*) FILTER (WHERE q.pit_deferred)
    INTO v_open_before, v_available, v_deferred
  FROM public.conflict_sweep_queue q;

  FOR r IN
    -- Candidates the resolver can actually act on. PIT-deferred rows are left
    -- OPEN and unresolved on purpose (migration 133 owns that judgement); they
    -- are merely no longer allowed to occupy the age-ordered head of the queue.
    SELECT q.id FROM public.conflict_sweep_queue q
    WHERE NOT q.pit_deferred
      AND (p_types IS NULL OR q.conflict_type = ANY(p_types))
    ORDER BY q.created_at ASC
    LIMIT p_limit
  LOOP
    BEGIN
      v_res := public.resolve_conflict_auto(r.id, p_actor);
      v_action := v_res->>'action';
    EXCEPTION WHEN OTHERS THEN
      -- One bad row must not abort the sweep.
      v_errors := v_errors + 1;
      v_action := 'error';
    END;
    IF v_action = 'skipped' THEN
      v_skipped := v_skipped + 1;
    END IF;
    v_total := v_total + 1;
    v_actions := jsonb_set(v_actions, ARRAY[v_action],
                           to_jsonb(COALESCE((v_actions->>v_action)::integer, 0) + 1));
  END LOOP;

  SELECT count(*) INTO v_open_after FROM public.conflict_sweep_queue;

  INSERT INTO public.conflict_sweep_runs (
    actor, sweep_limit, open_before, candidates_available, pit_deferred,
    processed, adjudicated, skipped, errors, actions, open_after)
  VALUES (p_actor, p_limit, v_open_before, v_available, v_deferred,
          v_total, v_total - v_skipped - v_errors, v_skipped, v_errors,
          v_actions, v_open_after);

  RETURN jsonb_build_object(
    'processed', v_total,
    'adjudicated', v_total - v_skipped - v_errors,
    'skipped', v_skipped,
    'errors', v_errors,
    'actions', v_actions,
    'candidates_available', v_available,
    'pit_deferred_not_selected', v_deferred,
    'open_conflicts_remaining', v_open_after);
END;
$$;

COMMENT ON FUNCTION public.sweep_conflicts(integer, text, text[]) IS
  'Batch driver for resolve_conflict_auto() (migration 063; candidate set narrowed by 137). Called daily by contradiction_scan.py right after scan_memory_contradictions(). Candidates come from conflict_sweep_queue WHERE NOT pit_deferred, so the p_limit budget is never spent re-skipping point-in-time conflicts the resolver refuses by design and never resolves — those blocked the age-ordered head of the queue from 2026-08-24 to 2026-08-26. Per-row exception handling retained. Every call appends to conflict_sweep_runs; read `adjudicated`/`skipped` there, not `processed`.';

REVOKE EXECUTE ON FUNCTION public.sweep_conflicts(integer, text, text[]) FROM anon, authenticated;
